"""create dashboard tables

Revision ID: 8ff9e2b4db2e
Revises: 
Create Date: 2026-05-16 16:04:46.790105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ff9e2b4db2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('poles',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('classification', sa.String(length=120), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('height_ft', sa.Float(), nullable=True),
    sa.Column('above_grade_ft', sa.Float(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('circuit', sa.String(length=120), nullable=False),
    sa.Column('lean_degrees', sa.Float(), nullable=True),
    sa.Column('lean_status', sa.String(length=120), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_confidence', sa.String(length=80), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=40), nullable=True),
    sa.Column('installed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poles_circuit'), 'poles', ['circuit'], unique=False)
    op.create_index(op.f('ix_poles_sector'), 'poles', ['sector'], unique=False)
    op.create_index(op.f('ix_poles_severity'), 'poles', ['severity'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('initials', sa.String(length=8), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pole_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('open', 'snoozed', 'approved', 'dismissed', name='report_status'), nullable=False),
    sa.Column('submitted_by_user_id', sa.String(length=64), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pole_id'], ['poles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submitted_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_pole_id'), 'reports', ['pole_id'], unique=False)
    op.create_index(op.f('ix_reports_severity'), 'reports', ['severity'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_index(op.f('ix_reports_submitted_at'), 'reports', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_reports_submitted_by_user_id'), 'reports', ['submitted_by_user_id'], unique=False)
    op.create_table('field_photos',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pole_id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=True),
    sa.Column('label', sa.String(length=160), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('storage_key', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=True),
    sa.Column('severity_label', sa.String(length=120), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(length=64), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pole_id'], ['poles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_photos_pole_id'), 'field_photos', ['pole_id'], unique=False)
    op.create_index(op.f('ix_field_photos_report_id'), 'field_photos', ['report_id'], unique=False)
    op.create_index(op.f('ix_field_photos_severity'), 'field_photos', ['severity'], unique=False)
    op.create_index(op.f('ix_field_photos_uploaded_by_user_id'), 'field_photos', ['uploaded_by_user_id'], unique=False)
    op.create_table('pole_history_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('pole_id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Enum('report', 'comment', 'inspection', 'upgrade', 'joint_use', 'treatment', 'install', 'other', name='history_event_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_user_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('critical', 'high', 'medium', 'low', name='severity'), nullable=True),
    sa.Column('pin_color', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pole_id'], ['poles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pole_history_events_author_user_id'), 'pole_history_events', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_pole_history_events_event_date'), 'pole_history_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_pole_history_events_pole_id'), 'pole_history_events', ['pole_id'], unique=False)
    op.create_index(op.f('ix_pole_history_events_report_id'), 'pole_history_events', ['report_id'], unique=False)
    op.create_index(op.f('ix_pole_history_events_severity'), 'pole_history_events', ['severity'], unique=False)
    op.create_index(op.f('ix_pole_history_events_type'), 'pole_history_events', ['type'], unique=False)
    op.create_table('report_notes',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('report_id', sa.String(length=64), nullable=False),
    sa.Column('author_user_id', sa.String(length=64), nullable=False),
    sa.Column('content', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_notes_author_user_id'), 'report_notes', ['author_user_id'], unique=False)
    op.create_index(op.f('ix_report_notes_report_id'), 'report_notes', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_notes_report_id'), table_name='report_notes')
    op.drop_index(op.f('ix_report_notes_author_user_id'), table_name='report_notes')
    op.drop_table('report_notes')
    op.drop_index(op.f('ix_pole_history_events_type'), table_name='pole_history_events')
    op.drop_index(op.f('ix_pole_history_events_severity'), table_name='pole_history_events')
    op.drop_index(op.f('ix_pole_history_events_report_id'), table_name='pole_history_events')
    op.drop_index(op.f('ix_pole_history_events_pole_id'), table_name='pole_history_events')
    op.drop_index(op.f('ix_pole_history_events_event_date'), table_name='pole_history_events')
    op.drop_index(op.f('ix_pole_history_events_author_user_id'), table_name='pole_history_events')
    op.drop_table('pole_history_events')
    op.drop_index(op.f('ix_field_photos_uploaded_by_user_id'), table_name='field_photos')
    op.drop_index(op.f('ix_field_photos_severity'), table_name='field_photos')
    op.drop_index(op.f('ix_field_photos_report_id'), table_name='field_photos')
    op.drop_index(op.f('ix_field_photos_pole_id'), table_name='field_photos')
    op.drop_table('field_photos')
    op.drop_index(op.f('ix_reports_submitted_by_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_submitted_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_severity'), table_name='reports')
    op.drop_index(op.f('ix_reports_pole_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('users')
    op.drop_index(op.f('ix_poles_severity'), table_name='poles')
    op.drop_index(op.f('ix_poles_sector'), table_name='poles')
    op.drop_index(op.f('ix_poles_circuit'), table_name='poles')
    op.drop_table('poles')
    # ### end Alembic commands ###
