"""create violation types table

Revision ID: ca23e5649cb3
Revises: 8ff9e2b4db2e
Create Date: 2026-05-16 16:10:36.457211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ca23e5649cb3'
down_revision: Union[str, None] = '8ff9e2b4db2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('violation_types',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column(
        'default_severity',
        postgresql.ENUM('critical', 'high', 'medium', 'low', name='severity', create_type=False),
        nullable=True,
    ),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_violation_types_code'), 'violation_types', ['code'], unique=True)
    op.create_index(op.f('ix_violation_types_default_severity'), 'violation_types', ['default_severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violation_types_default_severity'), table_name='violation_types')
    op.drop_index(op.f('ix_violation_types_code'), table_name='violation_types')
    op.drop_table('violation_types')
    # ### end Alembic commands ###
