"""model nesc violation specs

Revision ID: cb6102218faa
Revises: ca23e5649cb3
Create Date: 2026-05-16 16:18:55.568225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb6102218faa'
down_revision: Union[str, None] = 'ca23e5649cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('violation_type_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_reports_violation_type_id'), 'reports', ['violation_type_id'], unique=False)
    op.create_foreign_key(
        'fk_reports_violation_type_id_violation_types',
        'reports',
        'violation_types',
        ['violation_type_id'],
        ['id'],
    )
    op.add_column('violation_types', sa.Column('standard_org', sa.String(length=80), server_default='IEEE', nullable=False))
    op.add_column('violation_types', sa.Column('standard_code', sa.String(length=80), server_default='IEEE C2', nullable=False))
    op.add_column(
        'violation_types',
        sa.Column('standard_name', sa.String(length=160), server_default='National Electrical Safety Code', nullable=False),
    )
    op.add_column('violation_types', sa.Column('edition_year', sa.Integer(), server_default='2023', nullable=False))
    op.add_column('violation_types', sa.Column('nesc_part', sa.String(length=160), nullable=True))
    op.add_column('violation_types', sa.Column('nesc_section', sa.String(length=160), nullable=True))
    op.add_column('violation_types', sa.Column('rule_number', sa.String(length=40), nullable=True))
    op.add_column('violation_types', sa.Column('subrule', sa.String(length=40), nullable=True))
    op.add_column('violation_types', sa.Column('table_number', sa.String(length=40), nullable=True))
    op.add_column('violation_types', sa.Column('violation_family', sa.String(length=80), server_default='general', nullable=False))
    op.add_column('violation_types', sa.Column('measurement_kind', sa.String(length=80), nullable=True))
    op.add_column('violation_types', sa.Column('measurement_unit', sa.String(length=40), nullable=True))
    op.add_column('violation_types', sa.Column('comparator', sa.String(length=16), nullable=True))
    op.add_column('violation_types', sa.Column('threshold_value', sa.Float(), nullable=True))
    op.add_column('violation_types', sa.Column('applicability', sa.JSON(), nullable=True))
    op.add_column('violation_types', sa.Column('evidence_required', sa.Text(), nullable=True))
    op.add_column('violation_types', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('violation_types', sa.Column('notes', sa.Text(), nullable=True))
    op.create_index(op.f('ix_violation_types_edition_year'), 'violation_types', ['edition_year'], unique=False)
    op.create_index(op.f('ix_violation_types_nesc_part'), 'violation_types', ['nesc_part'], unique=False)
    op.create_index(op.f('ix_violation_types_rule_number'), 'violation_types', ['rule_number'], unique=False)
    op.create_index(op.f('ix_violation_types_table_number'), 'violation_types', ['table_number'], unique=False)
    op.create_index(op.f('ix_violation_types_violation_family'), 'violation_types', ['violation_family'], unique=False)
    op.alter_column('violation_types', 'standard_org', server_default=None)
    op.alter_column('violation_types', 'standard_code', server_default=None)
    op.alter_column('violation_types', 'standard_name', server_default=None)
    op.alter_column('violation_types', 'edition_year', server_default=None)
    op.alter_column('violation_types', 'violation_family', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_violation_types_violation_family'), table_name='violation_types')
    op.drop_index(op.f('ix_violation_types_table_number'), table_name='violation_types')
    op.drop_index(op.f('ix_violation_types_rule_number'), table_name='violation_types')
    op.drop_index(op.f('ix_violation_types_nesc_part'), table_name='violation_types')
    op.drop_index(op.f('ix_violation_types_edition_year'), table_name='violation_types')
    op.drop_column('violation_types', 'notes')
    op.drop_column('violation_types', 'source_url')
    op.drop_column('violation_types', 'evidence_required')
    op.drop_column('violation_types', 'applicability')
    op.drop_column('violation_types', 'threshold_value')
    op.drop_column('violation_types', 'comparator')
    op.drop_column('violation_types', 'measurement_unit')
    op.drop_column('violation_types', 'measurement_kind')
    op.drop_column('violation_types', 'violation_family')
    op.drop_column('violation_types', 'table_number')
    op.drop_column('violation_types', 'subrule')
    op.drop_column('violation_types', 'rule_number')
    op.drop_column('violation_types', 'nesc_section')
    op.drop_column('violation_types', 'nesc_part')
    op.drop_column('violation_types', 'edition_year')
    op.drop_column('violation_types', 'standard_name')
    op.drop_column('violation_types', 'standard_code')
    op.drop_column('violation_types', 'standard_org')
    op.drop_constraint('fk_reports_violation_type_id_violation_types', 'reports', type_='foreignkey')
    op.drop_index(op.f('ix_reports_violation_type_id'), table_name='reports')
    op.drop_column('reports', 'violation_type_id')
    # ### end Alembic commands ###
